### ISSUE TITLE
useAzureCommunicationCallAdapter wont accept an array of user Id as locator. 

### ISSUE THREAD

**Issue by jorgecolon413** [Azure/communication-ui-library#2747] opened 2023-02-13 13:21 UTC
Following the documentation on the UI Library for the ```CallComposite 1:N Get Started``` in: 
https://azure.github.io/communication-ui-library/?path=/story/quickstarts-1ton--page 

Just noticed that the ```useAzureCommunicationCallAdapter``` won't accept the type of the locator pass down from the ``` useAzureCommunicationServiceArgs ``` function. 
I just copy and pasted the block of code, didn't modify anything. 

The error previously described:  
```
Argument of type '{ userId: CommunicationUserIdentifier; displayName: string; credential: AzureCommunicationTokenCredential | undefined; locator: { ...; }; }' is not assignable to parameter of type 'Partial<AzureCommunicationCallAdapterArgs>'.
  Types of property 'locator' are incompatible.
    Type '{ participantIds: string[]; }' is not assignable to type 'CallAdapterLocator | undefined'.ts(2345)
```

Code as is from the demo: 
```
import { AzureCommunicationTokenCredential, CommunicationUserIdentifier } from '@azure/communication-common';
import {
  CallComposite,
  fromFlatCommunicationIdentifier,
  useAzureCommunicationCallAdapter
} from '@azure/communication-react';
import React, { useMemo } from 'react';

/**
 * Authentication information needed for your client application to use
 * Azure Communication Services.
 *
 * For this quickstart, you can obtain these from the Azure portal as described here:
 * https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/identity/quick-create-identity
 *
 * In a real application, your backend service would provide these to the client
 * application after the user goes through your authentication flow.
 */
const USER_ID = '<Azure Communication Services Identifier>';
const TOKEN = '<Azure Communication Services Access Token>';

/**
 * Display name for the local participant.
 * In a real application, this would be part of the user data that your
 * backend services provides to the client application after the user
 * goes through your authentication flow.
 */
const DISPLAY_NAME = '<Display Name>';

/**
 * A list of ACS User IDs to call
 */
const ACS_USER_IDS = ['<ACS User ID>'];

/**
 * Entry point of your application.
 */
function App(): JSX.Element {
  // Arguments that would usually be provided by your backend service or
  // (indirectly) by the user.
  const { userId, token, displayName, participantIds } = useAzureCommunicationServiceArgs();

  // A well-formed token is required to initialize the chat and calling adapters.
  const credential = useMemo(() => {
    try {
      return new AzureCommunicationTokenCredential(token);
    } catch {
      console.error('Failed to construct token credential');
      return undefined;
    }
  }, [token]);

  // Memoize arguments to `useAzureCommunicationCallAdapter` so that
  // a new adapter is only created when an argument changes.
  const callAdapterArgs = useMemo(
    () => ({
      userId: fromFlatCommunicationIdentifier(userId) as CommunicationUserIdentifier,
      displayName,
      credential,
      locator: { participantIds }
    }),
    [userId, credential, displayName, participantIds]
  );
  const callAdapter = useAzureCommunicationCallAdapter(callAdapterArgs);

  if (callAdapter) {
    return (
      <div style={{ height: '100vh', display: 'flex' }}>
        <CallComposite adapter={callAdapter} />
      </div>
    );
  }
  if (credential === undefined) {
    return <h3>Failed to construct credential. Provided token is malformed.</h3>;
  }
  return <h3>Initializing...</h3>;
}

/**
 * This hook returns all the arguments required to use the Azure Communication services
 * that would be provided by your backend service after user authentication depending on the user-flow.
 */
function useAzureCommunicationServiceArgs(): {
  userId: string;
  token: string;
  displayName: string;
  participantIds: string[];
} {
  return {
    userId: USER_ID,
    token: TOKEN,
    displayName: DISPLAY_NAME,
    participantIds: ACS_USER_IDS
  };
}

export default App;
```

**Comment by dmceachernmsft** [comment] 2023-02-13 17:07
Hi @jorgecolon413! Thanks for letting us know about the issue! could you please let us know the version of the UI library that you are using? 1:N calling and PSTN Calling are features that are currently in beta so that locator wont work if you are using one of our stable releases.

**Comment by jorgecolon413** [comment] 2023-02-13 17:12
Sure here are my dependencies:
```
"dependencies": {
    "@azure/communication-calling": "^1.4.4",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "^1.5.0",
    "@fluentui/react-components": "^9.14.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/react-hooks": "^3.4.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.49",
    "@types/react": "^16.9.49",
    "@types/react-dom": "^16.9.8",
    "bootstrap": "^5.2.3",
    "react": "~16.14.0",
    "react-bootstrap": "^2.7.0",
    "react-dom": "16.13.1",
    "react-router-dom": "^6.8.1",
    "react-scripts": "^5.0.1",
    "react-select": "^5.7.0",
    "react-test-renderer": "^16.14.0",
    "reactstrap": "^8.4.1",
    "typescript": "^4.7.4",
    "uuid": "^9.0.0",
    "web-vitals": "^2.1.4"
  },
```
So is it possible to make a call using this resources and notify the other end of an incoming call ? and vice versa?

**Comment by dmceachernmsft** [comment] 2023-02-13 17:22
So we will need to update a few things in your deps array: 
```
"dependencies": {
    "@azure/communication-calling": "1.9.1-beta.1",
    "@azure/communication-chat": "^1.2.0",
    "@azure/communication-react": "1.4.1-beta.1",
...
```
after you update those the code snippet should be able to make a outbound call with the right `userId` , `token`, and `participantIds` that you want to call.

so right now with our composites we only provide a experience for outbound calling. However you can create a 1:N outbound and inbound experience with our Stateful client and component layer experience. If you are interested in that I would check out these pages in our storybook:
- https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-statefulcallclient--page
- https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-1ton--page  <- bottom of page we provide a snippet on subscribing to incoming calls with our `statefulCallClient` and the `CallAgent`.

**Comment by alkwa-msft** [comment] 2023-02-13 18:33
Please get back to us if that works or if we can help out with any other questions.

**Comment by jorgecolon413** [comment] 2023-02-14 13:43
I'm traying to understand the outbound capabilities of the composite with this demo:
https://azure.github.io/communication-ui-library/?path=/story/composites-call-start1toncall--start-1-to-n-call-example 

But for that demo in particular, I'm getting the following error:
```
CallError: CallClient.createCallAgent: Failed to create call agent, call agent for this ACS Id already exists
    at toCallError (main.081f3dbe.iframe.bundle.js:1:252530)
    at _callee$ (main.081f3dbe.iframe.bundle.js:1:251751)
    at tryCatch (vendors~main.e1ece266.iframe.bundle.js:6:2462410)
    at Generator.invoke [as _invoke] (vendors~main.e1ece266.iframe.bundle.js:6:2462033)
    at Generator.throw (vendors~main.e1ece266.iframe.bundle.js:6:2463185)
    at CallContext_asyncGeneratorStep (main.081f3dbe.iframe.bundle.js:1:234234)
    at _throw (main.081f3dbe.iframe.bundle.js:1:234645) 
```
I'm certain, that I am providing valid tokens for both identities (User and Callees).
Here is a image of what the demo displays meanwhile:
![image](https://user-images.githubusercontent.com/58268872/218755427-12438a65-8e94-4de0-95b0-7a74a73cb7bb.png)

It would seem that, I can't use a previously created Id with its corresponding token? or am I missing something ?

**Comment by dmceachernmsft** [comment] 2023-02-15 17:06
If you are using the same id and token in two different clients the Calling SDK will give you that error. the reason why is that the userId that is used to create the `CallAgent` under the hood of our `CallAdapter` is used like a phone number. so we restrict that Id to one client. Please make sure that you are using 2 different id values and tokens, you should then see our composite and inbound sample render.

**Comment by dmceachernmsft** [comment] 2023-03-30 23:01
Closing since over month old. Please re open if still an issue! 😊

**Closed by dmceachernmsft** 2023-03-30 23:01 UTC

**Comment by fpereiramapfrepr** [comment] 2023-05-10 14:25
Hey @dmceachernmsft, I finally found some time to work on this. I currently have a ReactJS app that uses a CallComponent, which uses an ID to make a call to an ACS user (client on port 3000 in the examples). Additionally, I have another ReactJS app that uses stateful clients to receive incoming calls (client on port 3001 in the examples). The problem is that when I answer the call, the stateful client doesn't seem to correctly instantiate the components for the call itself. These code snippets were written following the examples provided in the UI Library Storybook.

Here are some examples of how the interaction looks:

![3a4e98e5-0a26-430a-a703-e01797589fd4](https://github.com/Azure/communication-ui-library/assets/100782509/8555eed7-f548-4313-9f6a-e523fa394124)


![e6946eca-4d02-4606-a2fc-656af2ff7c85](https://github.com/Azure/communication-ui-library/assets/100782509/22dd74bf-c0b7-4157-88a6-c50b25206cdd)

Here is the component that I use to make the call: 
```
import {
  AzureCommunicationTokenCredential,
  CommunicationUserIdentifier,
} from '@azure/communication-common';
import {
  CallComposite,
  fromFlatCommunicationIdentifier,
  useAzureCommunicationCallAdapter,
} from '@azure/communication-react';
import React, { useMemo } from 'react';


type CallMultipleProps = {
  userId: string;
  userToken: string;
  displayName: string;
};

const ACS_USER_IDS = [
  '<ACS User Id>',
];

export const CallMultiple = (props: CallMultipleProps): JSX.Element => {
  const { userId, userToken, displayName } = props;

  // Memoize arguments to `useAzureCommunicationCallAdapter` so that
  // a new adapter is only created when an argument changes.
  const callAdapterArgs = useMemo(
    () => ({
      userId: fromFlatCommunicationIdentifier(userId) as CommunicationUserIdentifier,
     displayName,
      credential: new AzureCommunicationTokenCredential(userToken),
      locator: { participantIds: ACS_USER_IDS },
    }),
    [userId, userToken, displayName]
  );

  const callAdapter = useAzureCommunicationCallAdapter(callAdapterArgs);

  return (
    <div style={{ height: '100vh', display: 'flex' }}>
      {callAdapter ? (
        <CallComposite adapter={callAdapter} />
      ) : (
        <h3>Initializing...</h3>
      )}
    </div>
  );
};
```

Here is the code of the stateful clients that receive the incoming call: 
```
import React, { useEffect, useMemo, useState } from 'react';
import {
  Call,
  CallAgent,
  GroupCallLocator,
  IncomingCall,
  IncomingCallEvent
} from '@azure/communication-calling';
import { AzureCommunicationTokenCredential } from '@azure/communication-common';
import {
  DEFAULT_COMPONENT_ICONS,
  createStatefulCallClient,
  StatefulCallClient,
  FluentThemeProvider,
  CallAgentProvider,
  CallClientProvider,
  CallProvider
} from '@azure/communication-react';
import { initializeIcons, registerIcons } from '@fluentui/react';
import CallingComponents from './Components/CallComponentsStateful';
import { IncomingCallToast } from './Components/IncomingCallToast';

initializeIcons();
registerIcons({ icons: DEFAULT_COMPONENT_ICONS });

function App(): JSX.Element {
  // User access token and ID
  const userAccessToken = '<ACS User Token>';
  const userId = '<ACS User Id>';

  // Initial group state
  const initGroup = { groupId: '' } as GroupCallLocator;
  const displayName = '<ACS User Name>';

  // State hooks
  const [statefulCallClient, setStatefulCallClient] = useState<StatefulCallClient>();
  const [callAgent, setCallAgent] = useState<CallAgent>();
  const [call, setCall] = useState<Call>();
  const [incomingCall, setIncomingCall] = useState<IncomingCall>();
  const [group, setGroup] = useState(initGroup);

  // Token credential for Azure Communication Services
  const tokenCredential = useMemo(() => {
    return new AzureCommunicationTokenCredential(userAccessToken);
  }, [userAccessToken]);

  // Fetch user token and initialize call client
  useEffect(() => {
    setStatefulCallClient(
      createStatefulCallClient({
        userId: { communicationUserId: userId }
      })
    );
  }, [userId]);

  // Create call agent once the call client is initialized
  useEffect(() => {
    if (callAgent === undefined && statefulCallClient) {
      const createUserAgent = async (): Promise<void> => {
        setCallAgent(await statefulCallClient.createCallAgent(tokenCredential, { displayName: displayName }));
      };
      createUserAgent();
    }
  }, [callAgent, statefulCallClient, tokenCredential, displayName, group]);

  // Join the call when call agent and group ID are available
  useEffect(() => {
    if (callAgent !== undefined && group.groupId) {
      setCall(callAgent.join(group));
    }
  }, [callAgent, group]);

  // Listen for incoming calls
  useEffect(() => {
    const incomingCallListener: IncomingCallEvent = ({ incomingCall }) => {
      setIncomingCall(incomingCall);
    };
    if (callAgent) {
      callAgent.on('incomingCall', incomingCallListener);
      return () => {
        callAgent.off('incomingCall', incomingCallListener);
      };
    }
  }, [callAgent]);

  // Set the group ID for the call
  const setGroupId = (group: string) => {
    setGroup(current => {
      return {
        groupId: group
      };
    });
  };

  // Reject the incoming call
  const onRejectCall = (): void => {
    if (incomingCall) {
      incomingCall.reject();
    }
    setIncomingCall(undefined);
  };

  // Accept the incoming call
  const onAcceptCall = async (): Promise<void> => {
    if (incomingCall) {
      const call = await incomingCall.accept();
      console.log(call);
      setGroupId(call.id);
    }
    setIncomingCall(undefined);
  };

  return (
    <>
      <FluentThemeProvider>
        {statefulCallClient && (
          <CallClientProvider callClient={statefulCallClient}>
            {callAgent && (
              <CallAgentProvider callAgent={callAgent}>
                {incomingCall && (
                  <IncomingCallToast
                    callerName={incomingCall.callerInfo.displayName}
                    onClickAccept={onAcceptCall}
                    onClickReject={onRejectCall}
                  />
                )}
                {call && (
                  <CallProvider call={call}>
                    {callAgent && <CallingComponents />}
                  </CallProvider>
                )}
              </CallAgentProvider>
            )}
          </CallClientProvider>
        )}
      </FluentThemeProvider>
    </>
  );
}

export default App;

```
and this is the CallComponent from the stateful client: 
```
import {
  usePropsFor,
  VideoGallery,
  ControlBar,
  CameraButton,
  MicrophoneButton,
  ScreenShareButton,
  EndCallButton,
  ParticipantsButton,
} from '@azure/communication-react';
import { mergeStyles, Stack } from '@fluentui/react';
import React, { useCallback, useState } from 'react';

function CallingComponents(): JSX.Element {
  // Extracting props for communication components
  const participantsButtonProps = usePropsFor(ParticipantsButton);
  const videoGalleryProps = usePropsFor(VideoGallery);
  const cameraProps = usePropsFor(CameraButton);
  const microphoneProps = usePropsFor(MicrophoneButton);
  const screenShareProps = usePropsFor(ScreenShareButton);
  const endCallProps = usePropsFor(EndCallButton);
  

  const [callEnded, setCallEnded] = useState(false);

  // Handler for ending the call
  const onHangup = useCallback(async (): Promise<void> => {
    await endCallProps.onHangUp();
    setCallEnded(true);
  }, [endCallProps]);

  // Render "CallEnded" component if the call has ended
  if (callEnded) {
    return <CallEnded />;
  }

  // Render the calling components
  return (
    <Stack className={mergeStyles({ height: '100%' })}>
      <div style={{ width: '100vw', height: '100vh' }}>
        {videoGalleryProps && <VideoGallery {...videoGalleryProps} />}
      </div>

      <ControlBar layout="floatingBottom">
        {cameraProps && <CameraButton {...cameraProps} />}
        {microphoneProps && <MicrophoneButton {...microphoneProps} />}
        {screenShareProps && <ScreenShareButton {...screenShareProps} />}
        {participantsButtonProps && <ParticipantsButton {...participantsButtonProps} />}
        {endCallProps && <EndCallButton {...endCallProps} onHangUp={onHangup} />}
      </ControlBar>
    </Stack>
  );
}

// Component for displaying call ended message
function CallEnded(): JSX.Element {
  return <h1>You ended the call.</h1>;
}

export default CallingComponents;

```
Also, some other questions that we have at the moment:

1. We did not create an event grid in the current tenant, yet the stateful client can still listen to the events of the incoming call. Is this because of the ACS SDK managing these events, or are we missing something in how these events are being handled?
2. When making a call in this manner where the composite is using the ID of a user to initiate the call, is the group ID automatically generated? If so, which property of this incoming call should I use to initiate the call component?
3. Is there a way to capture the necessary props to initiate a ```CallComposite``` using these stateful components? For example, subscribing to the event for the incoming call but using the call composite instead of using the individual components for the call.

If there is something else missing from this post that may help understand the problem a bit more, please let me know.

References:
https://azure.github.io/communication-ui-library/?path=/docs/examples-incomingcallalerts-incomingcalltoast--incoming-call-toast

https://azure.github.io/communication-ui-library/?path=/docs/quickstarts-1ton--page
