### ISSUE TITLE
While using Communication React call state does not change to Connected

### ISSUE THREAD

**Issue by sayayinR** [Azure/communication-ui-library#3575] opened 2023-09-09 04:24 UTC
**Describe the bug; what happened?**
Hi, I am tying out the beta version of Communication React. Below is the main code where I am starting a call. I get all different states of the call except for "Connected". Call is successfully connected and I can see inside the call object (screenshot attached) that call state does change to "Connected" but not sure why call.state does not give me the "Connected" state. Because of this I am not able to set the appropriate view. Please advise. 
In the below code I am testing with echo so you see the "Ringing" state but if I do a call with an azure communication user, the state never changes from "Connecting" to "Connected". 

```
  const [call, setCall] = useState<Call>();
  const [callState, setCallState] = useState<CallState>();
  
  const startCallHandler = useMemo(
    () => () => {
      if (callAgent) {
        try {
        // Testing with echo
          setCall(callAgent.startCall([{ id: "8:echo123" }]));
        } catch (err) {
          console.error(err);
        }
      }
    },
    [callAgent]
  );

 useEffect(() => {
    const stateChangeHandler= () => {
      if (call?.state) {
        setCallState(call?.state);
      }
    };

    call?.on("stateChanged", stateChangeHandler);

    return () => {
      call?.off("stateChanged", stateChangeHandler);
    };
  }, [call])
  
  console.log("callState", callState)
```

 
**What are the steps to reproduce the issue?**

**What behavior did you expect?**
Call is connected so call.state should return back "Connected"
**If applicable, provide screenshots:**
![image](https://github.com/Azure/communication-ui-library/assets/11239820/73da042d-0343-4dff-b485-943e1e6ed8b3)

![image](https://github.com/Azure/communication-ui-library/assets/11239820/a5698d10-7398-4abb-88fd-28fe5c73fce7)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable):  1.7.0-beta.2
- `@azure/communication-calling` npm package version (if applicable): 1.15.1-beta.1
- `@azure/communication-chat` npm package version (if applicable): 1.3.2-beta.3

- OS & Device: Windows 11

**Comment by alkwa-msft** [comment] 2023-09-13 02:19
Hello. Tried out some of your code. I took the liberty in adding a few things in to make it work and it looks like it worked.

A couple questions here. 

- Did we initiate the callAgent?
- When do we call startCallHandler?

(my example code)
```
import React, { useEffect, useMemo, useState } from 'react';
import './App.css';
import { Call, CallState } from '@azure/communication-calling';

function App(props: any) {  <-- I pass in the callAgent from outside as a prop
  const [call, setCall] = useState<Call>();
  const [callState, setCallState] = useState<CallState>();

  const startCallHandler = useMemo(
    () => () => {
      if (props.callAgent) {
        try {
        // Testing with echo
          setCall(props.callAgent.startCall([{ id: "8:echo123" }]));
        } catch (err) {
          console.error(err);
        }
      }
    },
    [props.callAgent]
  );

  useEffect(() => {  // <-- I added this to start the call
    startCallHandler();
  }, [])

 useEffect(() => {
    const stateChangeHandler= () => {
      if (call?.state) {
        setCallState(call?.state);
      }
    };

    call?.on("stateChanged", stateChangeHandler);

    return () => {
      call?.off("stateChanged", stateChangeHandler);
    };
  }, [call])

  console.log("callState", callState)

  return <></>
}

export default App;
```


Something to also add is every time we update the state of the component it will cause a re-render which would account for the times you are seeing an undefined call state. if you just console.log the call.state when you get it you will not incur unnecessarily re-renders and avoid undefined call state print outs.

**Comment by sayayinR** [comment] 2023-09-13 05:21
Thanks for the reply.
Answers to your questions.
1- Yes this component is wrapped by a call agent provider so I use useCallAgent to get the agent.
2- startCallHandler is called from a button inside a child component 

I believe in your example code, call will be started on load of this component. I'm trying to start the call from a child that receives this startCallHandler  as a prop

**Comment by alkwa-msft** [comment] 2023-09-13 15:26
I am going to close this issue as I have confirmed the correct states are being set up in the object. 

technically the event handler function should have been trigger and since you are changing the state it should have also caused a rerender which would have hit your console.log to say you are in a connected state. So perhaps with a fuller snippet I could try to debug further what might be going on.

I believe it is most likely your client-side code at this time that may have a bug in it which is not triggering the printout at the right time.  If you have another snippet for me to debug through I am happy to check it out.

**Closed by alkwa-msft** 2023-09-13 15:26 UTC
