### ISSUE TITLE
MessageThread: Auto-scroll to bottom not working on window resize

### ISSUE THREAD

**Issue by ciaoamigoschat** [Azure/communication-ui-library#4779] opened 2024-06-25 08:02 UTC
**Description:**
I am using the MessageThread component from @azure/communication-react to display a list of messages in a chat. When the browser window is resized, the component does not automatically scroll to the last message. This creates a usability issue as the user has to manually scroll down to see the new messages.

**Steps to Reproduce:**
Include the MessageThread component in a React application.
Populate the component with a list of messages.
Resize the browser window.

**Expected Behavior:**
The MessageThread component should automatically scroll to the last message when the window is resized.

**Actual Behavior:**
The MessageThread component does not scroll to the last message when the window is resized.

**Proposed Solution:**
Implement a scrollToBottom method in the MessageThread component that can be called manually to force the scroll to the last message. Alternatively, handle the automatic scroll to the bottom when the window is resized.

**Comment by jpeng-ms** [comment] 2024-06-25 16:06
Thanks for raising the issue, please let me to look into it and I will get you back :)

**Comment by jpeng-ms** [comment] 2024-06-26 17:26
Hi @ciaoamigoschat 

Thanks for the feature request and I appreciated your patient. We had an internal discussion about this, we think the best solution is to have some code on your side to achieve this behaviour rather than supporting it from UI library side, you can do something like this:


```ts

const scrollToBottom = useCallback((): void => {
  if (scrollDivRef.current) {
    scrollDivRef.current.scrollIntoView({ block: 'end', behavior: 'smooth' });
  }
}, []);

const scrollDivRef = useRef<null | HTMLDivElement>(null);

return (
  <div ref={scrollDivRef}>
    <MessageThread
      userId={userId}
      messages={[ ... ]}
    />
  </div>
)

```

As you can see, all we need to do is to create a `<div>` wrapper with a ref `scrollDivRef`, then you can have some listeners to wait for window size changes and call `scrollToBottom()`

in this recording, I made the leave call button to call `scrollToBottom()`


feel free to let me know if you have any other questions!

**Comment by jpeng-ms** [comment] 2024-07-03 06:54
Hi @ciaoamigoschat 

Thanks for providing your code snippets, it's very useful for me to debug and understand the issue you are facing. I was able to reproduce with the code you provided, when you have 'maxHeight' defined, the entire div is already in max height and there's nothing to scroll. What you want to do is to scroll the the content within the `div` therefore you need to have `ref` defined one layer down. Here's an example: 


```ts
return (
    <div id="view-wrapper">
      <div id="chat-thread-wrapper" style={{ maxHeight: '400px', overflowY: 'auto', outline: '1px solid grey' }}>
        <div id="chat-thread-content-view" ref={scrollDivRef}>
          <MessageThread
            userId={userId}
            messages={[ ...  ]}
          />
        </div>
      </div>
      <button id="chat-thread-button" style={{ display: 'block', margin: '30px auto' }} onClick={scrollToBottom}>
        Scroll to Bottom
      </button>
    </div>
);
```

Noticing how we have the `maxHeight` on a base view called `view-wrapper` and have the `ref` defined in a sub view called `chat-thread-content-view`

Let's see it in action: 


Give it a try and let me know if that works for you : )

**Comment by jpeng-ms** [comment] 2024-07-08 17:01
Hi @ciaoamigoschat it has been a while since we hear back from you so I will go ahead to close this issue for now, please reopen this issue at any time if you still have questions :)

**Closed by jpeng-ms** 2024-07-08 17:01 UTC
Labels: chat
