### ISSUE TITLE
createAzureCommunicationCallAdapter not acting async in @azure/communication-react

### ISSUE THREAD

**Issue by harrychy8** [Azure/communication-ui-library#693] opened 2021-08-18 03:31 UTC
**Describe the bug; what happened?**

**What are the steps to reproduce the issue?**
You can just use the same code in https://azure.github.io/communication-ui-library/?path=/docs/composites-call--join-existing-call. You will see that the page only renders after the createAzureCommunicationCallAdapter call is finished. Therefore I felt like that inside the function there is something that is NOT async.

**What behavior did you expect?**
Page render first, and the adapter loads on the side.

- OS & Device: Windows on  PC
- Browser: Google Chrome
- Version  92.0.4515.131

**Is there any additional information?**
Please reach out to me -- harchen@microsoft.com

**Comment by anjulgarg** [comment] 2021-08-18 19:32
Hi @harrychy8 
Thanks for reaching out to us.

If you look closely at the code, the page is configured to render only after the `adapter` state variable has been populated.

![image](https://user-images.githubusercontent.com/9782747/129960397-f2ce825d-bdc2-4f1a-a033-2ba178b0a0a4.png)

This adapter variable is being set only after the `createAzureCommunicationCallAdapter`  is finished.

This is an intended behavior. The features on the page depend upon this adapter and thus we render the page only after we know that the adapter has been initialized.

**Comment by harrychy8** [comment] 2021-08-18 20:15
Thank you @anjulgarg for the quick response. The issue is that ```return <>Initializing...</>;``` is not even rendered when ```createAzureCommunicationCallAdapter``` is not finished

**Comment by anjulgarg** [comment] 2021-08-18 20:23
That's strange. Could you share your code?
Since `return <>Initializing...</>;` is outside the conditional blocks it should run.

**Comment by anjulgarg** [comment] 2021-08-18 21:43
Closing this issue as this is being caused due to a next.js dynamic import of the component which is out of the scope of this library

**Closed by anjulgarg** 2021-08-18 21:43 UTC
Labels: status:triage
