### ISSUE TITLE
No outgoing sound/speakers found in Android browsers

### ISSUE THREAD

**Issue by jgarplind** [Azure/communication-ui-library#4582] opened 2024-05-07 15:24 UTC
**Describe the bug; what happened?**
When launching the `CallComposite` in any Android browser, including Android WebView, it does not find any speakers, and therefore also does not play any outgoing sound.

Using form factor `desktop` clearly shows an empty list, and form factor `mobile` just doesn't play any sound.

This has been tested on multiple devices (mobile phones as well as tablets, trying both connected to bluetooth speakers and just default sound), on both Chrome and Android WebView.

However, it does find microphones, which to me indicates that this is not a permissions issue.

**What are the steps to reproduce the issue?**
Open https://azure.github.io/communication-ui-library/?path=/story/composites-call-joinexistingcall--join-existing-call using Chrome and/or Android WebView on any Android device.

Speakers will not be selectable (this also applies to Mobile Edge), but more importantly there will be no outgoing sound (this only applies to Mobile Chrome / Android WebView, not Mobile Edge)

**What behavior did you expect?**
Since these are [supported browsers](https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#javascript-calling-sdk-support-by-os-and-browser), I expect that the outgoing sound should work, presumably by using the default sound option.

**If applicable, provide screenshots:**

Simple reproduction on mobile Android Chrome:
![image](https://github.com/Azure/communication-ui-library/assets/10069144/012fffee-281b-42bf-a0d3-5b7e588775f8)

For reference, the sound **works fine** when using **Teams** on the tablet in Edge, even though that client also claims it cannot find any speakers.
![image](https://github.com/Azure/communication-ui-library/assets/10069144/f4e31688-c184-4d7a-aceb-5a5b3112648b)

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): 1.15.0
- `@azure/communication-calling` npm package version (if applicable): 1.23.2
- `@azure/communication-chat` npm package version (if applicable): N/A

- OS & Device:
  - Android on Fairphone 4
  - Android on Samsung Galaxy Tab S7 FE 5G
- Browser: Google Chrome, Android WebView
- Browser Version: 124 / unknown

**Comment by alkwa-msft** [comment] 2024-05-07 15:50
Thanks for logging this issue. Will share with the team and get back to you on a response.

In the interim I am curious since this is an Android application you are building if we have properly configured the manifest to allow for audio sources? https://stackoverflow.com/questions/40236925/allowing-microphone-accesspermission-in-webview-android-studio-java

Have we been able to run a test where we can access our cameras for another android application you have built? We just want to remove potential issues where this could be an android app configuration issue.

**Comment by jgarplind** [comment] 2024-05-08 12:50
**UPDATE**: In the scenario where we made it work (using Teams on Edge), it seems to be _Edge_ rather than _Teams_ that makes the sound work, since we were also able to make it work on Edge using our own ACS instance.

**Comment by JamesBurnside** [comment] 2024-05-08 14:46
Hi @jgarplind, thanks for filing the issue.

I'll split these into two distinct issues, one is by design (technical limitation) and one is a bug.

#### 1. No speaker selection available on Android

This is by design (a technical limitation).

Speaker enumeration/selection isn't supported on Android Chrome, iOS Safari, nor macOS Safari per the [Azure Communication Services DeviceManager](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/manage-video?pivots=platform-web#notes) so we purposefully do not show the speaker selection and instead show an "Audio" selection on mobile and macOS that sets both the active microphone and speaker.

#### 2. No outgoing sound is played

This was a regression that happened in the 1.15.0 build of `@azure/communication-react`. We have a fix for this (https://github.com/Azure/communication-ui-library/pull/4539) in `[1.16.0-beta.1](https://www.npmjs.com/package/@azure/communication-react/v/1.16.0-beta.1)`, could you try this version out and see if this fixes your audio-out issues?

We have 1.16.0 scheduled to be released later this week or early next week that will include this fix.

**Comment by jgarplind** [comment] 2024-05-08 15:00
> Hi @jgarplind, thanks for filing the issue.
> 
> I'll split these into two distinct issues, one is by design (technical limitation) and one is a bug.
> 
> #### 1. No speaker selection available on Android
> 
> This is by design (a technical limitation).
> 
> Speaker enumeration/selection isn't supported on Android Chrome, iOS Safari, nor macOS Safari per the [Azure Communication Services DeviceManager](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/manage-video?pivots=platform-web#notes) so we purposefully do not show the speaker selection and instead show an "Audio" selection on mobile and macOS that sets both the active microphone and speaker.
> 
> #### 2. No outgoing sound is played
> 
> This was a regression that happened in the 1.15.0 build of `@azure/communication-react`. We have a fix for this (https://github.com/Azure/communication-ui-library/pull/4539) in [`1.16.0-beta.1`](https://www.npmjs.com/package/@azure/communication-react/v/1.16.0-beta.1), could you try this version out and see if this fixes your audio-out issues?
> 
> We have 1.16.0 scheduled to be released later this week or early next week that will include this fix.
> 

Thanks. Issue 2 is indeed the pressing issue.

Public holidays are starting literally in one minute here in Sweden, but we'll test the beta version and let you know by Monday.

Thanks a lot for the timely and clear response.

**Comment by jgarplind** [comment] 2024-05-13 06:35
Looping back to confirm that `@azure/communication-react@1.16.0-beta.1` (with peer `@azure/communication-calling@1.24.1-beta.2`) makes the sound work as expected 🎉

**Comment by JamesBurnside** [comment] 2024-05-13 15:27
Appreciate the testing and response, we have release `1.16.0` stable version that should have the same fix also. Closing this issue but please file another if you run into the same problem or have any other issues or feedback

**Closed by JamesBurnside** 2024-05-13 15:27 UTC
