### ISSUE TITLE
Scrolling indicator is not moving when you scroll up/down in SendBox flyout suggestions for a mention

### ISSUE THREAD

**Issue by musale** [Azure/communication-ui-library#3828] opened 2023-11-24 11:29 UTC
**Describe the bug; what happened?**
In `SendBox`, using the `@mention` feature shows a flyout with suggestions. Intuitively, one scrolls through the list with up/down arrow keys on the keyboard. However, the scrolling does not get triggered.

**What are the steps to reproduce the issue?**
- Use the `@mentions` feature in `SendBox` or go to https://azure.github.io/communication-ui-library/?path=/docs/ui-components-sendbox--send-box#mentioning-users
- Type `@`.
- Suggestions flyout pops up.
- Scroll down with arrow key until the last item in the suggestions.
- You see the scroll indicator not moving down when you get out of the view of currently shown suggestions.

**What behavior did you expect?**

Scrolling with the keyboard on the flyout should work the same way as scrolling with a mouse.

**If applicable, provide screenshots:**
https://github.com/Azure/communication-ui-library/assets/8081536/1e547bbf-7f43-4394-b857-26eb05381a98

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.10.0-beta.1]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.16.3]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.3.2]

- OS & Device: Windows
- Browser: Microsoft Edge
- Browser Version: 119.0.2151.72 (Official build)

**Is there any additional information?**

**Comment by jpeng-ms** [comment] 2023-11-24 18:28
Hi @musale, I have checked with our team, this is indeed a bug on our side. I have created an item and will let you know once it's fixed

**Comment by jpeng-ms** [comment] 2023-11-24 18:38
3514430

**Comment by vhuseinova-msft** [comment] 2024-01-05 22:38
Hi @musale! 
I just wanted to share a quick update, the issue is fixed and will be included in the next release

**Comment by jpeng-ms** [comment] 2024-02-02 21:55
Hi @musale the new beta is now available: https://www.npmjs.com/package/@azure/communication-react/v/1.13.0-beta.1

Please give a try and let me know if you have any other questions. I will go ahead and close off this issue for now, but feel free to reopen it if you have any issues.

**Closed by jpeng-ms** 2024-02-02 21:55 UTC
Labels: chat composite
