### ISSUE TITLE
CallComposite shows non-existent “unnamed participant” when joining Teams meeting

### ISSUE THREAD

**Issue by picorel** [Azure/communication-ui-library#3695] opened 2023-10-19 22:13 UTC
We are using the `CallComposite` component to join Teams meetings. 

We are using `@azure/communication-react: 1.7.0-beta.2`, and we want to upgrade to the latest beta version (`1.9.0-beta.1`),
However, the `CallComposite` shows two non-existent “unnamed participants” when joining a Teams meeting. 

We could also reproduce it in the `CallComposite` component from Storybook. 
https://azure.github.io/communication-ui-library/?path=/story/composites-call-joinexistingcall--join-existing-call

![two unnamed participants in call composite from storybook](https://github.com/Azure/communication-ui-library/assets/74991114/4ac6f271-3d3a-4706-97bd-0b186a33183a)

Steps to reproduce:

- Create a Teams meeting.
- Create an ACS user. 
- Join the meeting as the ACS user using the Teams meeting link.
- Teams UI shows the correct participants in the meeting. 
- Call Composite shows two “Unnamed participants”.  

Is it possible to prevent this behavior, or is it a known issue? 

Environment: 

- "@azure/communication-calling": "1.17.1-beta.5".
- "@azure/communication-calling-effects": "1.0.1".
- "@azure/communication-chat": "1.4.0-beta.1".
- "@azure/communication-react": "1.9.0-beta.1".
- And also in the Storybook component. 
- OS & Device: MacOS.
- Browser: Chrome.

Thanks

**Comment by PorterNan** [comment] 2023-10-19 23:18
Thanks for raising the issue! Just wanted to confirm - it is reproducible in 1.9.0-beta.1 but 1.7.0-beta.1 works fine, is this a correct understanding?

**Comment by picorel** [comment] 2023-10-20 01:38
> Thanks for raising the issue! Just wanted to confirm - it is reproducible in 1.9.0-beta.1 but 1.7.0-beta.1 works fine, is this a correct understanding?

Yes, exactly. 
Thanks

**Comment by JamesBurnside** [comment] 2023-10-25 22:11
Hi @picorel, taking a look we're unable to reproduce the issue you are seeing

![image](https://github.com/Azure/communication-ui-library/assets/2684369/4ac1e0b7-1006-4a51-a375-c80e6410b429)

Could I get a few more details from you to dig deeper into the problem:

1. Could you repro locally and share with us the `callId`? You can find the callId under `adapter?.getState().call?.id;`
2. Could you share the version of Microsoft Teams you are using?
3. Could you verify you see the same issue when using the teams web client? (teams.microsoft.com) - and if possible the version of Teams in the browser?
4. Do you see any important errors in the browser console window?

**Comment by picorel** [comment] 2023-10-26 19:17
Hi @JamesBurnside, 
We have two tenants. 
Testing it again, the issue is now reproducible when joining meetings from one of our tenants. It is not reproducible when joining meetings from the other tenant.

In the tenant that happens, the issue is reproducible with both Teams Desktop and Web clients. The Desktop version I’m using is 1.6.00.27656 (Mac OS). 

Here is one example of the call id when seeing the issue:
CallId was first `c41d9f46-02bf-4a3d-af87-0f6f4d62b8f2`, and then `e4f61bfc-0efc-400d-b0d4-1740389e3f31`.

The acs app was using:

- "@azure/communication-calling": "1.17.1-beta.5",
- "@azure/communication-calling-effects": "1.0.1",
- "@azure/communication-chat": "1.4.0-beta.1",
- "@azure/communication-react": "1.9.0-beta.1",

There were no errors in the console. 

In this case, I joined the meeting from Teams side with the Teams Web client.

**Comment by JamesBurnside** [comment] 2023-10-27 15:52
Thanks @picorel for the information. The two unnamed participants in the call are Teams bots. Depending on how the tenant and meeting is setup this would explain why certain meetings are seeing this behavior while others are not.

There was a breaking change in the beta version of one of our dependencies ([`@azure/communication-common`](https://www.npmjs.com/package/@azure/communication-common) npm package) where they rolled back releasing a new major version (`3.0.0-beta.1`) and instead released a minor version (`2.3.0`). Between these versions they updated an identifier field from `microsoftBot` to `microsoftTeamsApp` which is used for filtering out these system bots.

`@azure/communication-react` is aiming to release `1.10.0-beta.1` beta version next week that also uses the newer communication-common 2.x.x version which should hopefully resolve the issue.

**Comment by picorel** [comment] 2023-10-27 22:21
Thanks for the information @JamesBurnside. 

Which version is the component from Storybook using? Is it stable? 
https://azure.github.io/communication-ui-library/?path=/story/composites-call-joinexistingcall--join-existing-call

I could reproduce the issue there.

**Comment by JamesBurnside** [comment] 2023-11-03 19:36
New release is out, @picorel can you try the new release and see if you are still hitting the same issue?
https://www.npmjs.com/package/@azure/communication-react/v/1.10.0-beta.1

(`@azure/communication-react@1.10.0-beta.1/@azure/communication-calling@1.19.1-beta.2/@azure/communication-chat@1.4.0-beta.2`)

**Comment by picorel** [comment] 2023-11-07 13:35
@JamesBurnside, I tried to test it in my local environment, but the latest release doesn’t compile for us.
If the change is expected, we’ll need to review our babel configuration. 

<img width="557" alt="communication calling failed to compile" src="https://github.com/Azure/communication-ui-library/assets/74991114/45e7b1da-d29b-48dd-9c7f-0fa5d5cf76b8">


I tested a meeting in the Storybook component https://azure.github.io/communication-ui-library/?path=/story/composites-call-joinexistingcall--join-existing-call, which I guess it is now using the latest beta release `@azure/communication-react": "1.10.0-beta.1”`. I still see two unnamed participants there.

**Comment by picorel** [comment] 2023-11-17 12:54
Hi @JamesBurnside. Yes, the People pane shows the bots (it shows 4 participants when only 2 users are in the meeting). 
I tested it in the version `@azure/communication-react: 1.9.0-beta.1`.

**Comment by JamesBurnside** [comment] 2024-01-09 21:45
The downstream fix took some time to be published but we have a new version out in place for this issue. The new versions to use are:

- `@azure/communication-calling@1.19.2-beta.2`
- `@azure/communication-react@1.11.0-beta.2`

All future versions will include the fixes also.

@picorel I will keep this issue open for some time to test in case you run into any further issues and then close it in a few days.

**Comment by JamesBurnside** [comment] 2024-02-05 22:45
Closing this as the issue should be fixed.

**Closed by JamesBurnside** 2024-02-05 22:45 UTC
