### ISSUE TITLE
How to support multiple chat threads (using UI-Components)

### ISSUE THREAD

**Issue by DrDaveH** [Azure/communication-ui-library#3210] opened 2023-06-15 10:33 UTC
We have a requirement to handle multiple concurrent chat thread conversations when using the communication-ui-library. Ideally we would like to use the UI Components (along with the stateful client), as the ability to customize the UI is an important factor. The requirement is to be able to switch between a number of different chat threads that the user is a participant of (in a similar manner to which the Teams Client allows). Having already attempted numerous different methods to achieve this, we have encountered a number of different issues (bugs?) with each, and hence are reaching out for any advice that anyone can possibly provide.

In our particular use-case, a user will only be a participant in a limited number of active chat threads simultaneously (say about 6 concurrent chat threads). Due to this, we attempted using _n_ "Chat thread" components concurrently, i.e., instantiating _n_ Stateful chat clients and MessageThread components  (UI Component approach) or _n_ chatApapters (Composite Approach). In our case we simply hide (using z-index) the non-current chat thread component(s). With both these approaches we are witnessing the same issues;

1. Instantiating _n_ Stateful Clients/chatAdapters concurrently results in real-time notifications not working for all threads.

    For example, modifying the code in https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/ui-library-starting-with-chat-stateful (UI Component Approach) or the code from 
multi-chat-thread-js-bundle-app.txt (given in Issue #2058) (Composite Approach) to have two simultaneous chat thread views, means the creation of two WebScokets for real-time chat notifications, however, from our testing, chat messages to the user are only being presented over one of the WebSockets. This means that we only see new messages sent to one of the two chat threads and not both. From what we can determine, this problem only happens when the WebSockets are created at pretty much the same time, and it looks to be an issue with either the underlying JavaScript Chat library or the ACS service itself, rather than the UI component.

2. A new chat message received by the user on one thread, causes other message thread components to re-render their contents (Assuming the above issue is avoided by instantiating at separate times).

    This is obviously more of a performance concern than functionally but we've found that in our 2 simultaneous chat thread tests (both UI Component and Composite Approaches as mentioned above), sending a new message to one of the user's chat threads causes both chat thread components to re-render all their messages.

Rather than having multiple components, we've also tried using just the one component (UI Component Approach) and updating the chatThreadClient on chat thread switching. We've attempted two different approaches for this with differing results;

1. Not re-instantiating the statefulChatClient on each chat thread switch.

    This appears to work pretty well and avoids message reloads when switching back and forth between chat threads but we witness an issue in that once you've scrolled to the top of one chat thread, if you then switch to another chat thread, it isn't possible to scroll back to see older messages in that thread. We suspect some shared state within the statefulChatClient is causing this. 

2. Re-instantiating the statefulChatClient on each chat thread switch.

    We figured that this approach was the most likely to work, albeit at the expense of re-loading the messages each time your switch between threads. However we can't get it to work completely and there doesn't appear to be any sample(s) which perform a similar task. Using the https://github.com/Azure/communication-ui-library/tree/main/samples/ComponentExamples as a starting point we've amended it to allow switching between a number of predefined chat threads. This again works quite well but suffers from the issue that the chat pane does not update when a new message for that thread is received. Furthermore, this looks to be an issue with the base code (without our multi-chat thread modifications) and doesn't appear to be a WebSocket issue, as we can see the new message arrive in the browser network debugger.

All testing was performed using @azure/communication-react v1.5.0 and Public Preview 1.5.1-beta.5

Any help on what the recommended method is, and how to achieve it, will be most appreciated, ideally using the UI Components/statefulChatClient rather than the Chat Composite.

Many thanks in advance, cheers Dave

**Comment by palatter** [comment] 2023-06-19 16:50
Dave,

Thank you for reaching out and providing such a detailed investigation for your own efforts for multiple thread support.

This is something we are looking at with our product group currently. We can update you here with more information regarding the status of it.

**Comment by DrDaveH** [comment] 2023-06-20 13:24
Thanks for the response. Yeah, any update will be most appreciated.

**Comment by emlynmac** [comment] 2023-06-22 18:44
Hi @DrDaveH,
Thanks for a thorough description of the issue and steps attempted to work around.

The underlying chat layers have a chat client and a chat thread client. The chat thread client represents the thread and has a 1:1 mapping to a chat thread, while the chat client has many threads and maintains the notifications for all threads. 

I suspect that using multiple chat clients will attempt to cause multiple websockets, which I believe will not work and hence the behaviour you're seeing in the first case.

I'll have more details next week when I've had a chance to really dig into the details, in the mean time this article may be helpful if you have not seen it already:

https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/chat/get-started?tabs=windows&pivots=programming-language-javascript#start-a-chat-thread 

Thanks for your patience,

**Comment by emlynmac** [comment] 2023-06-28 21:14
@DrDaveH,
I've had a chance to dig a little deeper here. I've been able to build out a simple example with two simultaneous chats operating on-screen with messages and notifications appearing in the correct MessageThread components.

The code to achieve this:
```
// FILL IN AS NEEDED
const threadId =
const secondThreadId =
const token = 
const endpointUrl = '
const userId = 

export const Examples = (): JSX.Element => {
  const [chatClient, setChatClient] = useState<StatefulChatClient>();
  const [chatThreadClient, setChatThreadClient] = useState<ChatThreadClient>();
  const [chatThreadClient2, setChatThreadClient2] = useState<ChatThreadClient>(); 

  useEffect(() => {
    (async () => {
      const displayName = 'Example user';
      const credential = new AzureCommunicationTokenCredential(token);
      // set up chat client
      const chatClient = createStatefulChatClient({
        credential,
        userId: { communicationUserId: userId },
        displayName,
        endpoint: endpointUrl
      });
      // start realtime notification
      chatClient.startRealtimeNotifications();

      setChatClient(chatClient);
      setChatThreadClient(chatClient.getChatThreadClient(threadId));
      setChatThreadClient2(chatClient.getChatThreadClient(secondThreadId));
    })();
  }, []);

  const chatContainer = chatClient && chatThreadClient && (
    <ChatClientProvider chatClient={chatClient}>
      <ChatThreadClientProvider chatThreadClient={chatThreadClient}>
        <ComponentExample />
      </ChatThreadClientProvider>
    </ChatClientProvider>
  );

  const chatContainer2 = chatClient && chatThreadClient2 && (
     <ChatClientProvider chatClient={chatClient}>
        <ChatThreadClientProvider chatThreadClient={chatThreadClient2}>
          <ComponentExample />
        </ChatThreadClientProvider>
      </ChatClientProvider>
  );

  return (
    <FluentThemeProvider>
      <Stack verticalFill>
        <Stack horizontal>
          <div style={{ position: 'relative', width: '50%' }}>
            {chatContainer}
          </div>
          <div style={{ position: 'relative', width: '50%' }}>
            {chatContainer2}
          </div>
        </Stack>
      </Stack>      
    </FluentThemeProvider>
  );
  ```
If this doesn't get you to your goals, can you share your code or an example of what functionality you wish to achieve and I can have a further look? 
`ComponentExample` is from here: https://github.com/Azure/communication-ui-library/blob/main/samples/ComponentExamples/src/examples/ComponentExample.tsx

**Comment by DrDaveH** [comment] 2023-07-04 13:49
Hi @emlynmac, many thanks for your response and code suggestion. It is much appreciated.

One of our previous tests (not documented in the initial post) did attempt essentially the same thing; having a single statefulChatClient and multiple chatThreadClients. Since your example code is slightly different, we've tested your code and can report that we witness the same issues with both programs;

1. If the chat threads have existing messages, then it takes quite some time to initially render them (longer than with a different approach). We think this is down to each chat thread component causing the other component to re-render multiple times on message loading. This becomes more noticeable if there are more than two chat threads.
2. As mentioned in the original post, a new chat message received by the user on one thread, causes other message thread components to re-render their contents.
3. Scrolling back to see older messages is really slow if the component needs to reload further messages. It appears that scrolling up in one chat thread causes the other chat thread component to re-render its messages multiple times. We are seeing it take around 9-10 seconds for the scroll bar to re-position after loading further messages.

Issues 1 & 3 are probably the most noticeable and problematic in practice. It may well be that all three issues are related as they appear to be all caused by unnecessary re-rendering.

Are you seeing any similar problems?

Once again, many thanks.

**Comment by emlynmac** [comment] 2023-07-04 16:42
Hi @DrDaveH,

I've got a branch and logging in place where I can see all the updates happening.
I can reproduce the scrolling up causing both message threads to re-render. 
I'm investigating where this is happening.

Thanks for your patience

**Comment by emlynmac** [comment] 2023-07-06 16:14
Good morning @DrDaveH!
I merged a PR to our main branch that should resolve the performance issues. We have a nightly alpha build that should contain this fix tomorrow. Please give this version a try and see if it resolves the problem for you.

Thanks,

**Comment by DrDaveH** [comment] 2023-07-11 08:43
Hi  @emlynmac, many thanks once again for your help.

We've tried the 1.7.0-alpha-202307080015 build package in our test apps, and can report that the issues are greatly improved. However, we believe there is still a slight issue as regards scrolling back.

In general, scrolling back is much faster (the same as with a single component) but under certain circumstances it can still be very slow. We think the situation is caused by swapping between chat threads whilst scrolling in each.

For example; in chat thread 1 scroll up a bit so that new messages are loaded, then switch to chat thread 2 and do the same. Then switch back to chat thread 1 and again scroll up so that new messages need to be loaded via the HTTP API call. We experience a delay at this point which appears to be proportional to the number of messages already displayed in that chat thread (note, if the messages are already cached, and there is no HTTP call, then the scrolling is as fast as normal). You will probably only really notice this if there are many messages in the chat thread but we've seen it take around 7 seconds to reposition the scroll bar when the chat component is already displaying 110 messages.

Is this something that could be looked into?

Any help will be greatly appreciated.

**Comment by emlynmac** [comment] 2023-07-11 15:04
Hi @DrDaveH,

I'm glad to hear that the overall performance has improved.

For the use case you've outlined above, can you provide some sample code and traces from the browser debug tools? It would be most interesting to see how long the calls take and the ordering and rendering cycles.

In my basic testing I was able to scroll up in the two message panes in a performant manner, but I may not have the same number of messages involved. It could be that the logic around how the MessageThread component is loading up messages might need some tuning for your use case or something entirely different.

**Comment by DrDaveH** [comment] 2023-07-13 14:46
Hi @emlynmac , thanks again for your help.

I've hopefully managed to get all the logging/info you require.

I've attached the following;

- 	MsMultiChat.zip (this is essentially the source code you kindly provided previously)
- 	localhost-1689255726739.log (Browser Console log)
- 	Trace-20230713T142733.json (Browser Performance trace)

You will notice I've added some logging in the ComponentExample.tsx source file to log changes to messageThreadProps(.messages) and also to log rendering of individual messages.

In the console log you can see that between 14:25:13.061 & 14:25:24.574 there is logging showing rendering of different messages whilst messageThreadProps.messages is constantly recorded as being of length 145 messages - this is the 11 second delay in performing the scrolling.

Please let me know if there's anything else you require. I do also have the browser network capture but didn't want to post it on GitHub.

Once again, many thanks.
[MsMultiChat.zip](https://github.com/Azure/communication-ui-library/files/12040621/MsMultiChat.zip)
[localhost-Logs.zip](https://github.com/Azure/communication-ui-library/files/12040623/localhost-Logs.zip)

**Comment by emlynmac** [comment] 2023-07-18 18:02
@DrDaveH just to confirm, to reproduce this delay, I need to overlap the loading of messages in both chat threads at the same time?

**Comment by DrDaveH** [comment] 2023-07-19 08:42
@emlynmac , not at the same time, just one after the other. I believe it's the switching between scrolling in one chat thread and then the other, which causes the issue.

You may be able to see this in the screen shots present in the browser performance trace I provided, if you scroll through the timeline.

**Comment by emlynmac** [comment] 2023-08-08 16:40
@DrDaveH apologies for the radio silence; I'm finding some time next week to look at this. Things have been rather busy lately.

**Comment by emlynmac** [comment] 2023-08-14 18:03
@DrDaveH,

I found some time to get back to the dual chat pane and I've not been able to reproduce any significant latency issues with scrolling and message loading between the two. I have been using our main branch for this with a twin-pane chat set up, and a couple of fairly lengthy chat threads.

We're cutting a release from the main branch soon, so please let me know if that release improves things when it is out.

The fix that was put in previously should have resolved the case of the selector layer being recreated for each chat's thread ID, which resolved the duplicate rendering here. The linked PR above has details of the fix, it would be great if you could verify that part is working as intended in your code.

**Comment by vhuseinova-msft** [comment] 2023-08-30 15:35
We are closing this issue since we haven’t heard back from you for 10 days. Feel free to reopen this issue if you have any questions.

**Closed by vhuseinova-msft** 2023-08-30 15:35 UTC
Labels: question, status:triage, chat
