### ISSUE TITLE
Mention rendering getting stripped in MessageThread

### ISSUE THREAD

**Issue by Adr-Mark** [Azure/communication-ui-library#3602] opened 2023-09-20 22:54 UTC
**Describe the bug; what happened?**
When using the mention feature with the SendBox and MessageThread components, on sending the message the mention renders correctly but then it rerenders as plain text. Logging shows that the message is being sent initially with the <msft-mention> tags but rerendering with no tags.

**What are the steps to reproduce the issue?**
In SendBox, change the message contentType to be sent as "html" (The default "text" contentType just displays the tags as plain text) and send a message with a mention. The mention will initially show with the rendering specified in onRenderMention, then will change to plain text.

**What behavior did you expect?**
That the rendering that is initially shown will not change.

**In what environment did you see the issue?**
"@azure/communication-chat": "^1.3.2",
"@azure/communication-react": "^1.8.0-beta.1"

**Is there any additional information?**
Workaround: The current workaround is to have SendBox send the message with the "text" contentType, then manually change the messages array that is passed to the MessageThread component so each message has a contentType of "html".

**Comment by JoshuaLai** [comment] 2023-09-20 23:31
Thanks for raising this issue, I will be investigating into it and will keep you post here with what I find.

**Comment by JoshuaLai** [comment] 2023-09-21 17:26
@Adr-Mark I just wanted to follow I have tested this on our side with our samples and confirmed it is an issue. Thanks for bringing this up! I will add this to our bug backlog and prioritize it.

**Comment by JoshuaLai** [comment] 2023-09-21 21:29
@Adr-Mark can you confirm one thing for me in your code. 
I found that if I don't use the send box props that our component `const sendBoxProps = usePropsFor(SendBox);` this issue seems to go away. 
```js 
        {
          <SendBox
            onSendMessage={async (content: string): Promise<void> => {
              const options: SendMessageOptions = {
                type: "html",
              };
              props.threadClient.sendMessage({ content }, options);
              return Promise.resolve();
            }}
            mentionLookupOptions={{
              trigger,
              onQueryUpdated: async (query: string) => {
                const filtered = suggestions.filter((suggestion) => {
                  return suggestion.displayText
                    .toLocaleLowerCase()
                    .startsWith(query.toLocaleLowerCase());
                });
                return Promise.resolve(filtered);
              },
            }}
          />
        }
```
Can you confirm whether or not you are using the `const sendBoxProps = usePropsFor(SendBox);`. If so can you try removing it?  I think something in our default behaviour is causing the message bubbles to re-render but haven't quite found the culprit yet.

**Comment by Adr-Mark** [comment] 2023-09-21 21:42
@JoshuaLai Yes we are using sendBoxProps. I will remove it and let you know how it goes.

**Comment by Adr-Mark** [comment] 2023-09-21 22:16
@JoshuaLai Removing the sendBoxProps and using your code has not resolved this in our case. The logs show the message renders three times, with the tags on the first two renders, then without them on the third. This also happens when using the mention feature while editing a message in the MessageThread.

**Comment by JoshuaLai** [comment] 2023-09-21 22:23
Thanks for the update. I am seeing the removal of the tags as well on my side as well. I will continue to investigate why this is happening and keep you posted.

**Comment by JoshuaLai** [comment] 2023-09-22 21:32
We are investigating on the best way to fix this. For this time being I think the work around of sending the message out as content-type `text`. Then having the stateful chat client convert the content-type back to `html` might be the best solution so far. We will update this git issue again when we have find a more ideal solution as we evolve our public preview

**Comment by JoshuaLai** [comment] 2023-11-14 20:22
Since there is a temporary solution for this git issue. I will be closing this. As we update our APIs with new capability I will update this git issue.

**Closed by JoshuaLai** 2023-11-14 20:22 UTC
Labels: chat
