### ISSUE TITLE
Question about testing changes in my app

### ISSUE THREAD

**Issue by managedcoder** [Azure/communication-ui-library#3110] opened 2023-05-27 02:29 UTC
In the [doc for testing changes in my app](https://github.com/Azure/communication-ui-library/blob/main/docs/contributing-guide/4.%20testing-your-changes.md#testing-changes-in-your-app) it says, `rush build -t "package-name`.  I've made some changes to SendBox and InputBoxComponent but I am not sure what the `package-name ` shoud be.  How do I figure out the package-name I need to build if I've changed those two components?

Also, I have an app that I am building using latest shipped version of the UI Library but once I figure out the question I mentioned above, I will want to install that customized package(s) in my app among the other un-customized UI Library packages.  Do I have to uninstall the shipping version of the customized package before I install the customize `package-name.tar.gz` package.

**Comment by jpeng-ms** [comment] 2023-05-29 04:41
Hi Russ, 

Thanks for reaching out to us again. Since `Sendbox` is under the package of `@internal/react-components` you would need to run:

`rush build -t @internal/react-components`

Then go to `communication-ui-library/packages/react-components/` and run `npm pack`, then a `.tgz` file would be created under this folder. In addition, please note that `react-components` is depend on other two packages - `@internal/northstar-wrapper` and `@internal/acs-ui-common` - you would need to do the same thing for them as well. That is, you need to build and pack them to `.tgz` files.

After that, you should now have three files - `internal-acs-ui-common-1.5.1-beta.4.tgz`, `internal-northstar-wrapper-1.5.1-beta.4.tgz` and `internal-react-components-1.5.1-beta.4.tgz`

let's go back to your app and place these three files in root directory of your project and run:
```
npm install internal-northstar-wrapper-1.5.1-beta.4.tgz internal-acs-ui-common-1.5.1-beta.4.tgz internal-react-components-1.5.1-beta.4.tgz
```

noticing in the `package.json` of your project it should now have a reference of these three packages like this:

```js
...
  "dependencies": {
    "@azure/communication-react": "^1.5.0",
    "@internal/acs-ui-common": "file:internal-acs-ui-common-1.5.1-beta.4.tgz",
    "@internal/northstar-wrapper": "file:internal-northstar-wrapper-1.5.1-beta.4.tgz",
    "@internal/react-components": "file:internal-react-components-1.5.1-beta.4.tgz",
...
```
now let's rename `@internal/react-components` to `@internal/react-components-custom` and in package.json and run `npm install` one last time. Then, you can then test your changes by importing any component you have modified from this custom package like this:

```js
import { SendBox as SendBoxModified } from '@internal/react-components-custom';
```

That's it! Feel free to raise a PR after testing your changes and we are excited to see your work. Let me know if you have any more questions!

John

**Comment by JoshuaLai** [comment] 2023-05-29 19:28
@managedcoder Please let us know if the above has clarify how you can test. If not let us know and we can try to help you out further

**Comment by managedcoder** [comment] 2023-05-30 12:06
@JoshuaLai & @jpeng-ms, those instructions worked perfectly.  After following them I was able to test my customizations in my app!  Thank you.

I am curious how I would figure out which dependencies a package has that would need to be built and installed for any given change one might do to a package so I'll know how to do that if I want to make a change to another package in the future.

I have run into another issue that I will submit separately rather than mix it into this one, so I think you can close this issue.

**Comment by jpeng-ms** [comment] 2023-05-30 16:34
Hi @managedcoder, I’m glad to know it works for you. For the package names, you can actually look it up in the `package.json` file of where your modified files is located under.

For example, for the `SendBox` component, you might found `package.json` located in its parent folder: https://github.com/Azure/communication-ui-library/blob/ef8bdc4425d095d12ad511e0e312f039bf2b0d46/packages/react-components/package.json#L2

Let me know if you have questions!

John

**Comment by JoshuaLai** [comment] 2023-05-30 16:34
> I am curious how I would figure out which dependencies a package has that would need to be built and installed for any given change one might do to a package so I'll know how to do that if I want to make a change to another package in the future.

I think the best is to go through our storybook and there may be a bit of reverse engineering needed to figure out which packages uses what object. 

Closing as the issue is now resolved.

**Closed by JoshuaLai** 2023-05-30 16:34 UTC
Labels: chat composite
