### ISSUE TITLE
Unable to join call on Chrome Canary

### ISSUE THREAD

**Issue by jerry-chuang-qhr** [Azure/communication-ui-library#4105] opened 2024-02-06 19:33 UTC
**Describe the bug; what happened?**
When using Chrome Canary browser (Tested with Version 123.0.6276.0 (Official Build) canary (arm64))

User can join a call and be sent to the audio/video test screen, but upon joining, user is immediately sent to "You have left the call" screen
Rejoining the call on that screen also immediately send user back to "You have left the call" screen

**What are the steps to reproduce the issue?**
This can be reproduced with the official example at https://azure.github.io/communication-ui-library/?path=/story/composites-call-joinexistingcall--join-existing-call. Only appears to be an issue on Chrome Canary browser

Enter required token/user id/call locator and join a call.

**What behavior did you expect?**
User should be able to join call as usual

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
can be reproduced with official example at https://azure.github.io/communication-ui-library/?path=/story/composites-call-joinexistingcall--join-existing-call

- OS & Device: MacOS 13.6.4 on 2021 Macbook Pro
- Browser: Google Chrome Canary
- Browser Version: 
Version 123.0.6276.0 (Official Build) canary (arm64) 
Version 123.0.6284.1 (Official Build) canary-dcheck (arm64)

**Is there any additional information?**

Hello, we were doing some testing and stumbled upon this issue where the calls appear to just not work at all on Chrome Canary. When we test on regular chrome (Version 121.0.6167.85 (Official Build) (arm64)), the call is behaving normally. Hopefully the issue doesn't come to regular Chrome, but wanted to make sure this is on you guys' radar.

**Comment by alkwa-msft** [comment] 2024-02-06 20:04
@jerry-chuang-qhr  dont suppose you have a console error of what happened when the call just failed?

**Comment by jerry-chuang-qhr** [comment] 2024-02-06 21:01
![Screenshot 2024-02-06 at 12 55 59 PM](https://github.com/Azure/communication-ui-library/assets/61984145/2c3355b9-29c3-4692-a707-d4c239ce65ce)

Clearing console log before joining, the only thing that popped up is the "Third-party cookie will be blocked. ..." issue.
At one point we thought this might be it, but third party cookie setting is set to allowed for both Canary and regular Chrome. And we also got the same console output on regular Chrome where joining call is working.

**Comment by edwardlee-msft** [comment] 2024-02-06 21:28
Hi @jerry-chuang-qhr, 
This is a pretty interesting scenario with chrome canary. I was able to reproduce your findings and will get back to you after conducting further investigation.

**Comment by edwardlee-msft** [comment] 2024-02-12 21:51
Hi @jerry-chuang-qhr,

Thank you for your patience. This issue is now fixed on the latest chrome canary chromium version. Please update to the latest chrome canary chromium version which as of writing is Version 123.0.6296.0.

Feel free to reopen this issue if the issue is still seen on your end after updating.

**Closed by edwardlee-msft** 2024-02-12 21:51 UTC
