### ISSUE TITLE
Cannot catch BrowserNotSupported exception in CallComposite

### ISSUE THREAD

**Issue by rubeonline** [Azure/communication-ui-library#2589] opened 2022-12-13 14:14 UTC
**Describe the bug; what happened?**

I cannot catch the BrowserNotSupported error. I tried it in that way:
`````
         adapter?.on("error", handleError);

         // i never reach this handleError Part
         const handleError = (e: Error) => {
              console.log(JSON.stringify(e));
          };
`````

**What are the steps to reproduce the issue?**

- Open it in Firefox on macOS

**What behavior did you expect?**

Reach the handleError part so i can show a message to the user, that his browser is not supported

**If applicable, provide screenshots:**

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/5664460/207354658-fa84c464-bb29-40f6-9647-ffb114e26bb7.png">

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version: 1.3.1
- `@azure/communication-calling` npm package version:  1.4.4

- OS & Device: [MacOS]
- Browser: [Mozilla FireFox]
- Browser Version: [108.0]

**Is there any additional information?**

**Comment by JamesBurnside** [comment] 2023-01-03 19:10
Hi @rubeonline, thanks for bringing this to our attention.

The issue here is caused by the CallClient ctor in `@azure/communication-calling`. This throws an error when the CallClient is constructed on an unsupported browser, and so the AzureCommunicationCallAdapter is also throwing an error on construction.

Just prefixing this response with the `@azure/communication-calling` package is working on making unsupported environment more actionable. In their beta packages they are exposing a new feature `DebugInfo` that has environment info: https://learn.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/browser-support.

Today, you can catch the error in two ways, the first is to keep using the `useAzureCommunicationCallAdapter` hook and wrap an [ErrorBoundary](https://reactjs.org/docs/error-boundaries.html) around your component to catch the error thrown inside the hook.
Alternatively you can switch to using the more fundamental `createAzureCommunicationAdapter` which you can directly wrap in a try-catch block:

```tsx
...

const [adapter, setAdapter] = useState<AzureCommunicationCallAdapter>();

useEffect(() => {
  const createAdapterAsync = () => {
    try {
      const callAdapter = await createAzureCommunicationCallAdapter({
        userId: // userId,
        displayName: //displayName,
        credential: new AzureCommunicationTokenCredential( /*token*/ ),
        locator: // locator
      });
      setAdapter(callAdapter);
    } catch (error) {
      // act on error
    }
  };

  createAdapterAsync();
}, [ /* useEffect deps */ ]);

...
```

In the near future, when the new environment info changes are made stable in a new communication-calling npm package, the adapter constructor will no longer throw an error in the constructor and instead will report whether the browser is supported through the environmentInfo. If you do then try to start a call on an unsupported browser it will throw an error as expected and this will be catchable using `adapter?.on("error", handleError);`

**Comment by dmceachernmsft** [comment] 2023-02-11 01:06
Resolution seems to have been given. closing due to age. please raise the issue again if it is still causing you issues! 😊

**Closed by dmceachernmsft** 2023-02-11 01:06 UTC

**Comment by rubeonline** [comment] 2023-03-07 13:08
@JamesBurnside Thank you for your answer. With the ErrorBoundary i also could not catch the error. But with the alternative `createAzureCommunicationAdapter ` it worked. Thanks.
