### ISSUE TITLE
Infinite spinning circle when sharing screen using the calling composite in a Teams meeting

### ISSUE THREAD

**Issue by ddematheu2** [Azure/communication-ui-library#2274] opened 2022-08-26 00:36 UTC
**Describe the bug; what happened?**
When in a Teams interop call, if the Teams user shares screen, the user on the call composite sees an infinite loading icon on the screen.

**What are the steps to reproduce the issue?**
Join a teams interop call from the call composite
Start screen sharing from the teams client

**What behavior did you expect?**
No loading icon

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.3.0]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.5.4-beta.1]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.2.2]

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
- Browser Version: [e.g. 1.8.0]

**Is there any additional information?**

**Comment by prprabhu-ms** [comment] 2022-08-26 05:20
This looks like a duplicate of https://github.com/Azure/communication-ui-library/issues/2186 and it is fixed in `@azure/communication-react@1.3.1` (in fact, `1.3.1` is a hot fix just for this bug).

Can you try bumping your dependency version and retrying?

**Comment by JamesBurnside** [comment] 2022-09-06 17:03
Closing this issue as a hotfix has been released in 1.3.1, please create a new issue if you are still seeing this in `@azure/communication-react@1.3.1`

**Closed by JamesBurnside** 2022-09-06 17:03 UTC
Labels: needs more info
