### ISSUE TITLE
Add Functionality for Background Blur in the 'communication-ui-library' 

### ISSUE THREAD

**Issue by grathore1999** [Azure/communication-ui-library#2842] opened 2023-03-27 06:44 UTC
**What feature are you requesting?**
I want a background blur feature in ACS CallWithChat Composite Project
**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by JamesBurnside** [comment] 2023-04-10 20:36
Closing as a duplicate of https://github.com/Azure/communication-ui-library/issues/2746

**Closed by JamesBurnside** 2023-04-10 20:36 UTC

**Comment by grathore1999** [comment] 2023-05-05 06:41
In the Azure/communication-ui-library, Can background blur be enabled on mobile devices? If so, when?
________________________________
