### ISSUE TITLE
"branding" option is not available in "1.14.0-beta.1"

### ISSUE THREAD

**Issue by lovedota** [Azure/communication-ui-library#4210] opened 2024-03-04 03:39 UTC
**Describe the bug; what happened?**
I install the 1.14.0-beta.1 but cannot use `branding` option

![Screen Shot 2024-03-04 at 10 38 34 AM](https://github.com/Azure/communication-ui-library/assets/417914/b37a6fb7-f2e7-40e0-ae54-591c521dfe7b)

**What are the steps to reproduce the issue?**

**What behavior did you expect?**

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

- `@azure/communication-react` npm package version (if applicable): [e.g. 1.3.0]
- `@azure/communication-calling` npm package version (if applicable): [e.g. 1.5.4-beta.1]
- `@azure/communication-chat` npm package version (if applicable): [e.g. 1.2.2]

- OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
- Browser: [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
- Browser Version: [e.g. 1.8.0]

**Is there any additional information?**

**Comment by dmceachernmsft** [comment] 2024-03-04 17:26
Hi @lovedota thanks for filing the issue we have found the issue that it was accidentally removed from the package. Is it possible to use `1.13.0-beta.1` until we make another release. It will return in all subsequent releases, this was done in error.

Sorry about that!

**Comment by lovedota** [comment] 2024-03-05 06:12
Hi @dmceachernmsft the `1.13.0-beta.1` doesn't have `branding` option also.

**Comment by dmceachernmsft** [comment] 2024-03-05 17:10
Thanks for letting me know! We will be looking into a hotfix to rectify this. will provide an update when we know more!

**Comment by dmceachernmsft** [comment] 2024-03-05 21:08
Hi @lovedota we released a new version 1.14.0-beta.2 https://www.npmjs.com/package/@azure/communication-react/v/1.14.0-beta.2 This reintroduces the branding feature. Apologies that this happened! Thanks very much for using our beta's very exciting you are using this feature to make your calling experiences your own!

Closing the issue as new release fixing the issue is out. please re-open the issue if you are still having trouble!

**Closed** 2024-03-05 21:08 UTC

**Comment by lovedota** [comment] 2024-03-06 00:33
Thanks @dmceachernmsft i worked.
