### ISSUE TITLE
When join a Teams Meeting, get CallError

### ISSUE THREAD

**Issue by hulin17** [Azure/communication-ui-library#4851] opened 2024-07-12 08:10 UTC
I use this sample: https://github.com/Azure-Samples/communication-services-authentication-hero-csharp

I can join a call with ACS token after login(The option1&option2).
But when I try to join a Teams Meeting(https://teams.microsoft.com/meet/xxxxxxx?p=xxxxxxx)(The option3&option4), I got below error:
CallError
    at toCallError (CallContext.js:644:1)
    at Proxy.<anonymous> (CallContext.js:625:1)
    at AzureCommunicationCallAdapter.js:272:1
    at AzureCommunicationCallAdapter.teeErrorToEventEmitter (AzureCommunicationCallAdapter.js:568:1)
    at AzureCommunicationCallAdapter.joinCall (AzureCommunicationCallAdapter.js:263:1)
    at Object.startCallHandler [as onClick] (CallComposite.js:61:1)
    at BaseButton._this._onClick (BaseButton.js:300:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3919:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3968:1)
    at invokeGuardedCallback (react-dom.development.js:4028:1) 
![image](https://github.com/user-attachments/assets/c8b22c1f-80a5-40c3-a8f5-d758ff26f53a)

What is confusing is the error does not have any useful info so I can not know what is happening.
![image](https://github.com/user-attachments/assets/2b8c0d79-09cf-461e-b4ce-b9b7c6a2cbdd)

**Comment by MarteenJL** [comment] 2024-07-12 16:58
Hi, I just saw this , when joining a teams meeting , the adapter should be a "TeamsCallAdapter" , not the "AzureCommunicationCallAdapter". HTH.  I don't work for MS , but do use the comm UI to make/start/join teams meetings.

**Comment by prabhjot-msft** [comment] 2024-07-12 18:25
@MarteenJL thanks for posting the issue, we are looking into it and will keep you posted with the updates.

**Comment by prabhjot-msft** [comment] 2024-07-15 23:01
@hulin17 looking into the repo, https://github.com/Azure-Samples/communication-services-authentication-hero-csharp/blob/0dedc73289e80857cc98b814da3061ce424af071/MinimalClient/src/components/TestCallTeamsUserContent.jsx#L69, seems like you are using the same adapter `createAzureCommunicationCallAdapter` for both ACS and for call as Teams user. Also, the token that is passed to adapter hook is `ACS token`.  If you are joining as Teams user, you need to use the `useTeamsCallAdapter` and pass the `Teams Access Token` to the adapter hook. 

Here is documentation with detailed code snippet you can refer to https://azure.github.io/communication-ui-library/?path=/docs/communicationasteamsuser--page. Let us know if this resolves the issue and how can we help further!

**Comment by MarteenJL** [comment] 2024-07-16 15:34
@hulin17 getting the teams token requires Azure function, and permissions, look at this sample:  https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/manage-teams-identity?pivots=programming-language-csharp
HTH

**Comment by hulin17** [comment] 2024-07-18 02:41
> Hi, I just saw this , when joining a teams meeting , the adapter should be a "TeamsCallAdapter" , not the "AzureCommunicationCallAdapter". HTH. I don't work for MS , but do use the comm UI to make/start/join teams meetings.

Thanks. @MarteenJL Already fixed this.

**Comment by prabhjot-msft** [comment] 2024-07-18 22:15
As the issue is fixed, closing the issue. @hulin17 feel free to reopen the issue in case you face the issue again.

**Closed by prabhjot-msft** 2024-07-18 22:15 UTC
