### ISSUE TITLE
CallComposite looping showing no errors

### ISSUE THREAD

**Issue by rdemace** [Azure/communication-ui-library#2813] opened 2023-03-14 11:55 UTC
Hi,

i was implementing CallComposite in my project with rooms implementation, versions below:

    "@azure/communication-calling": "^1.10.1",
    "@azure/communication-chat": "^1.3.1",
    "@azure/communication-common": "^2.2.0",
    "@azure/communication-react": "1.5.1-beta.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    
And i discovered that in this piece of code:

```
import { AzureCommunicationTokenCredential } from '@azure/communication-common';
import {
    CallComposite,
    useAzureCommunicationCallAdapter,
} from '@azure/communication-react';
import { useMemo } from 'react';

export const Test = (props: { token: string, userId: string, roomId: string }): JSX.Element => {

    const credential = useMemo(() => {
        try {
            return new AzureCommunicationTokenCredential(props.token);
        } catch (error) {
            console.error(error + '--- Failed to construct token credential');
            return undefined;
        }
    }, [props.token]);

    const adapter = useAzureCommunicationCallAdapter({
        userId: {
            communicationUserId: props.userId
        },
        options: {
            roleHint: 'Presenter'
        },
        displayName: 'Giorgio Rossi',
        credential,
        locator: {
            roomId: props.roomId
        }
    });

    return (
        <div style={{ height: '90vh', width: '90vw' }}>
            {adapter && (
                <CallComposite adapter={adapter} />
            )}
        </div>
    );
}
```

I get a loop in the console logs of chrome, with this messages:

![image](https://user-images.githubusercontent.com/127743194/224993025-3c844e0d-e02c-4d5f-a255-ceba4a7a2d64.png)

I don't know what could be causing it but if i delete this row:

        displayName: 'Giorgio Rossi',

and save with hot reload it stops the loop and let me create the call.

I discovered this randomly.

Thank you in advance

**Comment by prabhjot-msft** [comment] 2023-03-14 16:36
Thanks @rdemace for filing the issue. I am looking into it, will reach out if I am unable to reproduce the issue.

**Comment by prabhjot-msft** [comment] 2023-03-15 22:53
@rdemace I was able to repro the issue, the issue is caused by inline declaration of `displayName`. This issue can be resolved by memoizing the adapter arguments to ensure useAzureCommunicationCallAdapter is not retriggered on every render pass. I have attached a sample code snippet with memoized args. Closing the issue, feel free to reopen if you still see the issue.
<img width="924" alt="Screenshot 2023-03-15 at 3 44 07 PM" src="https://user-images.githubusercontent.com/97124699/225461125-7533fb85-a969-42cc-9f5a-9b2e55d602b3.png">

**Closed** 2023-03-15 22:54 UTC
