### ISSUE TITLE
Error in layout floatingLocalVideo of VideoGallery component

### ISSUE THREAD

**Issue by ricmeira** [Azure/communication-ui-library#2348] opened 2022-09-15 13:49 UTC
**Describe the bug; what happened?**
While executing VideoGallery with layout="floatingLocalVideo", sometimes the image does not show to the locallUser(remoteUser is still able to see the camera image). This is the error that appears in the console:
```
Uncaught (in promise) CallingCommunicationError: TypeError: Cannot read properties of null (reading 'size')
    at bf (sdk.bundle.js:100:98987)
    at e.<anonymous> (sdk.bundle.js:100:683370)
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at s (sdk.bundle.js:100:681850)
```

**What are the steps to reproduce the issue?**
It is an intermitent issue, don't know why it happens though, but from time tom time it happens while camera is turning on(camera image will not show for local participant, happens on multiple users).

**What behavior did you expect?**
Floating layout would show local camera image as expected instead og display name

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/1854914/190421501-054028a3-f30a-4dab-801f-cb35f230d572.png)

**In what environment did you see the issue?**

    "@azure/communication-react": "^1.3.0",
    "@azure/communication-calling": "^1.5.4",

- OS & Device: Windows on PC 
- Browser: Google Chrome
- Browser Version:  105.0.5195.102 64 bits

**Is there any additional information?**

**Comment by edwardlee-msft** [comment] 2022-09-15 15:38
Thanks for filing this issue, we'll take a look at this as soon as possible.

**Comment by mgamis-msft** [comment] 2022-09-22 06:41
Hi @ricmeira, Thank you for providing the information for this error. I was unable to reproduce the intermittent bug what you were seeing but I will investigate with the Calling SDK team which is our backend. I believe the console error you provided indicates the issue is in our backend.

How often would you say this happens?

**Comment by ricmeira** [comment] 2022-09-23 18:58
@mgamis-msft sorry late response, I saw it happening 3 to 4 times during my tests(lots of it). But we also had some QA users reporting this issue.

**Comment by anjulgarg** [comment] 2022-10-03 21:43
Hey @ricmeira 
Curious. Is this still an issue?

**Comment by ricmeira** [comment] 2022-10-11 14:11
@anjulgarg yes, it is

**Comment by JamesBurnside** [comment] 2022-11-07 22:40
Hi @ricmeira, apologies for the delay, this error typically occurs if the stream becomes undefined.
To enable us to help further we'll need a code snippet of how you are using the video gallery and passing in props, and if possible, record logs we can analyze. To gather logs can you create an azure logger in your app and redirect the output to the console:
```ts
import { setLogLevel } from '@azure/logger';
setLogLevel('info');
```

**Comment by mgamis-msft** [comment] 2022-11-08 03:06
Talked to the Calling SDK team and they are aware of this issue and say it could be a bug with their stream management or this could be hardware issue where a camera is longer available (which doesn't sound like the case as you are seeing this on multiple users.) They would like to see some logs to narrow down the cause of this intermittent error better.
If that does not work for you it would be great to see a code snippet from your test. Does it look something like our stateful quickstart [here](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/blob/main/ui-library-starting-with-calling-stateful/src/CallingComponentsStateful.tsx#L21)?

**Comment by ricmeira** [comment] 2022-11-14 19:40
Hello @mgamis-msft and @JamesBurnside I did as requested, and here are the logs that I receive when I get the console error:

![image](https://user-images.githubusercontent.com/1854914/201750160-3a217d57-ec2e-4aa5-a103-2c2d70021499.png)
![image](https://user-images.githubusercontent.com/1854914/201750316-bc8e5c6e-11ee-45c9-8b4c-ced1faa00c6a.png)

**Comment by fizampou** [comment] 2022-11-15 21:49
@ricmeira thanks for reporting that one. 

Can you attach the whole log file please? What i can see is so far is LocalVideoStream needs an target: HTMLElement and seems the element you are passing is not there. Is it possible it's removed/not attached to the DOM? 

Can you update to latest versions of npm packages and check again please?

**Comment by ricmeira** [comment] 2022-12-29 14:15
@mgamis-msft We had another big round of testing, what was noticed with these changes is that it is occuring less, but still occuring( after updating libs and the variable change)

@fizampou I was not able to reproduce it again, so I don't really have a log file, was reported by QA team. I will ask them to get the logs if they see it again

**Comment by ricmeira** [comment] 2023-01-11 15:28
@mgamis-msft @fizampou @anjulgarg After taking a look at it again, and some tests, found out a consitent way to make this bug happens. Seems that on the first call, the video shows as expected, after the second call, every video call has this error.

**Comment by mgamis-msft** [comment] 2023-01-22 10:43
@ricmeira Thank you for the details to reproduce this issue of no renderElement in the local video. 
I have 2 questions:
1.) Could you clarify what you mean by second call? Are you reusing the statefulcallclient to create new a call agent when loading the second call? 
If yes, this is not expected to cause this local stream to not show but it is interesting that you have found it to reliably reproduce this issue.
We were investigating this bug of 'Local video tile not showing video when camera was on' for a few months and have merged hot fix #2558 for version 1.4.1. 
2.) Could you verify your version is 1.4.1 or newer?

I would like to clarify these two questions first so I can try it on my side. Once again thank you so much for your feedback and details

**Comment by ricmeira** [comment] 2023-01-23 12:45
@mgamis-msft Still happening on 1.5.0

1- Yes, reusing the same statefullcallclient

Steps to reproduce:
1- Create StatefulCallClient
2- Create CallAgent
3- Start a call
4- Close call and dispose of the callAgent
5- Create a new CallAgent
6- Start new call, camera should not work anymore on local

**Comment by ricmeira** [comment] 2023-01-23 13:01
@mgamis-msft Still happening on 1.5.0

1- Yes, reusing the same statefullcallclient

Steps to reproduce:
1- Create StatefulCallClient
2- Create CallAgent
3- Start a call
4- Close call and dispose of the callAgent
5- Create a new CallAgent
6- Start new call, local camera should not show anymore on local

**Comment by mgamis-msft** [comment] 2023-01-24 09:19
@ricmeira I updated to "@azure/communication-calling": "1.9.1" and "@azure/communication-react": "1.5.0"
Ran this snippet of code with my userAccessToken, userId:
```
function App(): JSX.Element {
  const userAccessToken = '<Azure Communication Services Resource Access Token>';
  const userId = '<User Id associated to the token>';
  const groupId = '<Generated GUID groupd id>';
  const displayName = '<Display Name>';

  const [statefulCallClient, setStatefulCallClient] =
    useState<StatefulCallClient>();
  const [callAgent, setCallAgent] = useState<CallAgent>();
  const [call, setCall] = useState<Call>();

  useEffect(() => {
    setStatefulCallClient(
      createStatefulCallClient({
        userId: { communicationUserId: userId },
      })
    );
  }, []);

  useEffect(() => {
    const tokenCredential = new AzureCommunicationTokenCredential(
      userAccessToken
    );
    if (callAgent === undefined && statefulCallClient && displayName) {
      const createUserAgent = async () => {
        setCallAgent(
          await statefulCallClient.createCallAgent(tokenCredential, {
            displayName: displayName,
          })
        );
      };
      createUserAgent();
    }
  }, [statefulCallClient, displayName, callAgent]);

  useEffect(() => {
    if (callAgent !== undefined) {
      setCall(callAgent.join({ groupId }));
    }
  }, [callAgent]);

  return (
    <>
      <FluentThemeProvider>
        {statefulCallClient && (
          <CallClientProvider callClient={statefulCallClient}>
            {callAgent && (
              <CallAgentProvider callAgent={callAgent}>
                {call && (
                  <CallProvider call={call}>
                    <CallingComponents />
                  </CallProvider>
                )}
              </CallAgentProvider>
            )}
          </CallClientProvider>
        )}
      </FluentThemeProvider>
      <button
        onClick={() => {
          callAgent?.dispose();
          console.log('Call agent disposed');
          const tokenCredential = new AzureCommunicationTokenCredential(
            userAccessToken
          );
          console.log('Created new token credential');
          if (statefulCallClient && displayName) {
            const createUserAgent = async () => {
              setCallAgent(
                await statefulCallClient.createCallAgent(tokenCredential, {
                  displayName: displayName,
                })
              );
            };
            createUserAgent();
            console.log('Created new call agent');
          }
        }}
      >
        Start new call
      </button>
    </>
  );
}
and it looks like the CallClient instance can support only one CallAgent as shown in the error in this link to a video of me testing.
https://microsoft-my.sharepoint-df.com/:v:/p/miguelgamis/EXAM3WoLrgpPp8GBYOjYT0ABX6dtRQqLSVqAj-PQfR5F6g?e=9SehGh
Is your implementation much different than the code above? I imagine it is since you are at least able to start a 2nd call.

**Comment by ricmeira** [comment] 2023-01-24 12:25
@mgamis-msft It is similiar, only real difference is that the disposal of the call agent actually take a little time, so you can't really create a new call adapter right after you ask the disposal of the call adapter. In my case, I dispose the call agent if user logout from my app, and only recreate it if user logins again and try to execute a call. 
In this test file, maybe you can have one button to dispose the calladapter and another button to recreate call adapter and call again. So you would click to dispose, wait some small amount of time and click the second button to recreate call adapter/ call again.

**Comment by mgamis-msft** [comment] 2023-01-25 09:31
@ricmeira Thanks I am seeing what you are seeing now. The local video will not show consistently on the 2nd call but with this error
![image](https://user-images.githubusercontent.com/79475487/214527418-c40bbb41-b3cb-48b3-9f04-837e303058c8.png)
I will have a discussion with my team whether stateful call client can be reused. Will post back soon.

**Comment by mgamis-msft** [comment] 2023-01-26 09:46
@ricmeira There seems to be issues creating additional call agents with one stateful client and we are continuing to investigate.
In the meantime, we suggest to not dispose of the original call agent and use it join different calls like this simplified code below:
```
function App(): JSX.Element {
  const userAccessToken = '<Azure Communication Services Resource Access Token>';
  const userId = '<User Id associated to the token>';
  const displayName = '<Display Name>';

  const [statefulCallClient, setStatefulCallClient] =
    useState<StatefulCallClient>();
  const [callAgent, setCallAgent] = useState<CallAgent>();
  const [call, setCall] = useState<Call>();
  const [groupId, setGroupId] = useState<string>();

  useEffect(() => {
    setStatefulCallClient(
      createStatefulCallClient({
        userId: { communicationUserId: userId },
      })
    );
  }, []);

  useEffect(() => {
    const tokenCredential = new AzureCommunicationTokenCredential(
      userAccessToken
    );
    if (callAgent === undefined && statefulCallClient && displayName) {
      const createUserAgent = async () => {
        setCallAgent(
          await statefulCallClient.createCallAgent(tokenCredential, {
            displayName: displayName,
          })
        );
      };
      createUserAgent();
    }
  }, [statefulCallClient, displayName, callAgent]);

  return (
    <>
      <FluentThemeProvider>
        {statefulCallClient && (
          <CallClientProvider callClient={statefulCallClient}>
            {callAgent && (
              <CallAgentProvider callAgent={callAgent}>
                {call && (
                  <CallProvider call={call}>
                    <CallingComponents />
                  </CallProvider>
                )}
              </CallAgentProvider>
            )}
          </CallClientProvider>
        )}
      </FluentThemeProvider>
      <input
        onChange={(e) => {
          setGroupId(e.currentTarget.value);
        }}
        size={40}
      />
      <button
        onClick={async () => {
          if (callAgent && groupId) {
            setCall(callAgent.join({ groupId }));
            console.log("New call set");
          }
        }}
      >
        Join call
      </button>
    </>
  );
}
```
The following is a video of me testing the above code:
https://user-images.githubusercontent.com/79475487/214805141-0606bfad-7f5a-4537-bcb6-09d1c4c6bd39.mp4

**Comment by ricmeira** [comment] 2023-01-26 12:07
@mgamis-msft I am reusing the call agent during a session, but if user logout of the app, I have to dispose of it as it contains personal information. If user logins(or other user login) in same tab session), then I start getting the issue.

**Comment by mgamis-msft** [comment] 2023-01-28 01:05
To better understand why you are trying to explicitly dispose of the call agent, I'm curious what personal information are you concerned about? Are concerned about the userId, userToken, or the user's display name? Considering the life cycle of a react web app, React should dispose of the call agent when it is unmounted.

**Comment by ricmeira** [comment] 2023-01-30 17:12
@mgamis-msft All of them.
It does not dispose of the call agent when unmounted, you can confirm it if you want, just add a parent with a show/hide component to your code.
Something as simple as this:
```
export default function TestApp() {
  const [showComponent, setShowComponent] = useState(false);
  return (
    <>
      {showComponent? <App /> : null}
      <button onClick={() => {setShowComponent(!showComponent)}}>Show/Hide Component</button>
    </>
  );
}
```
You will see that whenever you show the component again you will receive this error on the console:
![image](https://user-images.githubusercontent.com/1854914/215545946-4e232f9f-39b8-4e07-ac9f-dedcfc7e66ae.png)

**Comment by ricmeira** [comment] 2023-03-29 13:22
@mgamis-msft Was there any updates on this issue?

**Comment by mgamis-msft** [comment] 2023-04-05 17:36
HI @ricmeira, did changing the callAgent to be managed by useRef instead of useState like the [above code](https://github.com/Azure/communication-ui-library/issues/2348#issuecomment-1413298338) not work for you? This should properly dispose of the callAgent when the App component is unmounted.

**Comment by JamesBurnside** [comment] 2023-07-17 15:07
This issue has had no activity for some time. Closing. Please reopen a new issue if you are still facing difficulties with this.

**Closed by JamesBurnside** 2023-07-17 15:07 UTC
Labels: investigate
